In [1]:
from attacks import *
from minority_class_experiments import *
from models.densenet import *

In [2]:
from experiment_utils import (set_device,
                              get_cifar_labels_to_ints,
                              get_cifar_ints_to_labels,
                              get_args,
                              print_duration,
                              get_transform)

labels_to_ints = get_cifar_labels_to_ints()
ints_to_labels = get_cifar_ints_to_labels()
train_data, valid_data, test_data = prepare_data(batch_size=64,
                                                 minority_class=labels_to_ints['cat'],
                                                 minority_percentage=1.)


train set: Files already downloaded and verified
0 4754
1 4749
2 4730
3 4756
4 4759
5 4741
6 4767
7 4767
8 4716
9 4761
val set: Files already downloaded and verified
0 246
1 251
2 270
3 244
4 241
5 259
6 233
7 233
8 284
9 239
test set: Files already downloaded and verified
0 1000
1 1000
2 1000
3 1000
4 1000
5 1000
6 1000
7 1000
8 1000
9 1000
Train: 47500, Valid: 2500, Test: 10000


In [5]:
"""
PGD attempts to find the perturbation that maximises the loss of a model 
on a particular input while keeping the size of the perturbation smaller 
than a specified amount referred to as epsilon. 


Adversarial training is simply putting the PGD attack inside your training loop. 
This is can be viewed as “ultimate data augmentation” as instead of performing 
random transformations (rescaling, cropping, mirroring etc.) as a preprocessing 
step we create specific perturbations that best fool our model and indeed adversarially 
trained models do exhibit less overfitting when trained on small datasets.
"""
model = DenseNet121()
for x, y in train_data:
    PGDAttack(x, model, y, True, 'images/test.png')
    break
#     inputs = x 
#     labels = y
#     inputs = nn.Parameter(inputs, requires_grad=True).to(inputs.device)
#     attacked_inputs = inputs.clone()
#     for i in range(10):
#         per_step_preds = model.forward(attacked_inputs)
#         loss = F.cross_entropy(input=per_step_preds, target=labels)
#         grads = torch.autograd.grad(inputs=[attacked_inputs], outputs=-loss)
#         attacked_inputs = attacked_inputs.clone() - 1000 * grads[0]
#     combined_inputs = torch.cat([inputs, attacked_inputs.detach()], dim=0)
#     combined_labels = torch.cat([labels, labels], dim=0)
#     break 

tensor([[ 0.1562,  0.0098,  0.0433,  0.0163, -0.3011, -0.0025, -0.0457,  0.0594,
          0.0078,  0.1482],
        [ 0.1238,  0.0542,  0.0766, -0.0767, -0.3373,  0.0296, -0.0820,  0.0881,
          0.0226,  0.0989],
        [ 0.1370,  0.0187,  0.2245, -0.3199, -0.2015, -0.1049,  0.0131,  0.1441,
          0.0628,  0.2137],
        [ 0.1125,  0.1225,  0.2503, -0.1073, -0.2609, -0.0887,  0.1436,  0.1832,
          0.0576,  0.1613],
        [ 0.1078,  0.1152,  0.1089, -0.0138, -0.1251, -0.0092,  0.0336, -0.0000,
         -0.0692,  0.1309],
        [ 0.1279,  0.0883,  0.0368, -0.0144, -0.0941, -0.0367, -0.0607,  0.0380,
         -0.1099,  0.1397],
        [ 0.0112, -0.0616,  0.0773, -0.1002, -0.0902, -0.1452, -0.0362,  0.1259,
          0.0468,  0.0881],
        [-0.0090,  0.1187,  0.0776,  0.0027, -0.0640, -0.0868,  0.0644,  0.0830,
          0.0531,  0.1249],
        [ 0.0943,  0.0088,  0.1550, -0.0909, -0.0732, -0.0979, -0.0887,  0.0512,
          0.0039,  0.2281],
        [ 0.0659,  

tensor([[-0.0405,  0.0379,  0.0512,  0.0129, -0.2592, -0.0485,  0.0086,  0.0748,
          0.0084,  0.2026],
        [ 0.1661,  0.0533,  0.0818, -0.0409, -0.3210,  0.0399, -0.0701,  0.0942,
          0.0794,  0.0013],
        [ 0.1305,  0.0250, -0.1033, -0.2086, -0.2523, -0.1277, -0.0112,  0.1666,
          0.0314,  0.2378],
        [ 0.0515,  0.1082,  0.2414, -0.0997, -0.2222, -0.1193, -0.0856,  0.2029,
          0.1242,  0.2062],
        [ 0.0726,  0.1842,  0.1806, -0.2288, -0.0829, -0.0825,  0.0779,  0.0713,
         -0.0972,  0.1540],
        [ 0.1886,  0.1588,  0.1167,  0.0016, -0.1095, -0.0318, -0.0335, -0.1330,
         -0.0869,  0.0940],
        [ 0.0791,  0.0816,  0.1197, -0.0422, -0.0729, -0.2011, -0.0598, -0.1022,
          0.0305,  0.0775],
        [ 0.0739,  0.1725,  0.1022, -0.0044, -0.2798, -0.0483,  0.1326,  0.0820,
          0.1322,  0.1108],
        [ 0.1063,  0.0796, -0.0778, -0.0362, -0.0841, -0.1501, -0.0974,  0.0890,
         -0.0290,  0.2499],
        [ 0.0902,  

tensor([[-0.0945,  0.0388,  0.0779,  0.0160, -0.2320, -0.0591,  0.0313,  0.1243,
          0.0144,  0.2096],
        [ 0.1750,  0.0899,  0.0863, -0.0264, -0.2910,  0.0772, -0.0566,  0.0846,
          0.0780, -0.0606],
        [ 0.1416,  0.0537, -0.2534, -0.1984, -0.2420, -0.0843, -0.0539,  0.2293,
          0.0098,  0.2306],
        [ 0.0108,  0.1022,  0.2050, -0.0935, -0.1570, -0.1397, -0.1530,  0.2167,
          0.1073,  0.2453],
        [ 0.1452,  0.1925,  0.2593, -0.3432, -0.0881, -0.0923,  0.1116,  0.1124,
         -0.1172,  0.1602],
        [ 0.1955,  0.1585,  0.1609,  0.0171, -0.1459, -0.0177, -0.0143, -0.1868,
         -0.0739,  0.1142],
        [ 0.0763,  0.0697,  0.1639, -0.0342, -0.0895, -0.2174, -0.0540, -0.1542,
          0.0695,  0.0538],
        [ 0.1197,  0.1952,  0.1177,  0.0024, -0.3481, -0.0194,  0.1577,  0.1147,
          0.1562,  0.1439],
        [ 0.0793,  0.0599, -0.1978, -0.0024, -0.1054, -0.1841, -0.0941,  0.1180,
          0.0078,  0.2872],
        [ 0.0598,  

tensor([[-0.1610,  0.0009,  0.0885,  0.0200, -0.2230, -0.0600,  0.0490,  0.1235,
          0.0356,  0.2540],
        [ 0.1834,  0.1187,  0.0673,  0.0087, -0.2857,  0.0807, -0.0765,  0.0850,
          0.0679, -0.0930],
        [ 0.1195,  0.0126, -0.3780, -0.1728, -0.2303, -0.0920, -0.1079,  0.2720,
         -0.0175,  0.2460],
        [ 0.0257,  0.0949,  0.2150, -0.0865, -0.1261, -0.1343, -0.2359,  0.2081,
          0.0859,  0.2677],
        [ 0.1715,  0.2533,  0.3026, -0.4046, -0.1017, -0.1054,  0.1207,  0.1297,
         -0.0811,  0.1627],
        [ 0.2096,  0.1473,  0.1975,  0.0080, -0.1750, -0.0236, -0.0130, -0.2508,
         -0.0420,  0.1166],
        [ 0.0475,  0.0834,  0.1571, -0.0283, -0.0728, -0.2214, -0.0663, -0.2142,
          0.0948,  0.0479],
        [ 0.1866,  0.1887,  0.0807, -0.0183, -0.4266,  0.0268,  0.1715,  0.1140,
          0.2227,  0.1287],
        [ 0.1197,  0.0777, -0.1845,  0.0118, -0.0916, -0.1454, -0.0997,  0.1189,
         -0.0314,  0.2509],
        [ 0.0731,  

tensor([[-0.2202,  0.0007,  0.0998,  0.0208, -0.1866, -0.0595,  0.0415,  0.1122,
          0.0094,  0.2259],
        [ 0.2160,  0.1326,  0.0581,  0.0321, -0.2898,  0.1247, -0.0489,  0.0775,
          0.0828, -0.1269],
        [ 0.1276,  0.0715, -0.3656, -0.1893, -0.2487, -0.0146, -0.0989,  0.2639,
         -0.0671,  0.2231],
        [ 0.0726,  0.1450,  0.2087, -0.0895, -0.1333, -0.1463, -0.2814,  0.2130,
          0.0808,  0.2613],
        [ 0.1146,  0.1777,  0.3028, -0.4682, -0.1165, -0.1002,  0.0896,  0.1357,
         -0.0922,  0.1784],
        [ 0.2157,  0.1621,  0.1815,  0.0120, -0.1678, -0.0378, -0.0138, -0.2593,
         -0.0402,  0.1258],
        [ 0.0767,  0.1042,  0.1633, -0.0353, -0.0828, -0.2080, -0.0431, -0.2762,
          0.0819,  0.0393],
        [ 0.1933,  0.2144,  0.0860, -0.0352, -0.4865,  0.0153,  0.1717,  0.1235,
          0.2128,  0.1362],
        [ 0.1152,  0.0912, -0.2403,  0.0120, -0.1264, -0.1689, -0.1045,  0.1264,
         -0.0242,  0.2809],
        [ 0.0491,  

torch.Size([64, 3, 32, 32]) tensor(7.1188) tensor(1.) tensor(0.)


In [ ]:
x.shape, combined_inputs.shape

In [ ]:
attacked_images = attacked_inputs.data.detach().cpu()
attacked_images = reverse_augmentations(attacked_images).unbind(0)
attacked_images = torch.cat(attacked_images, dim=1)
attacked_images = normalize(attacked_images)
attacked_images = transforms.ToPILImage()(attacked_images)
attacked_images

In [ ]:
images = inputs.data.detach().cpu()
images = reverse_augmentations(images).unbind(0)
images = torch.cat(images, dim=1)
images = normalize(images)
images = transforms.ToPILImage()(images)
images